### ISSUE TITLE
S3D features can not be downloaded

### ISSUE THREAD

**Issue by jpthu17** [antoine77340/howto100m#14]
Thank you for your dataset. 
But when I try to download s3d features by "wget http://howto100m.inria.fr:6885/howto100m_s3d_features/howto100m_s3d_features.zip" (wget https://howto100m.inria.fr:6885/howto100m_s3d_features/howto100m_s3d_features.zip), , I find it will be broken. How to solve this problem? Can you give some advises?

**Comment by michael-iuzzolino** [comment]
According to Antoine, Inria has turned off the server hosting the features so they are not available right now. The s3d features seem to be unavailable indefinitely.

**Comment by cws7777** [comment]
@michael-iuzzolino Hi, thank you for sharing the dataset. Do you know when this will be available again?

Thanks! :)

**Comment by antoine77340** [comment]
The s3d features are back here: You can find the S3D features here: http://howto100m.inria.fr/howto100m_s3d_features/howto100m_s3d_features.zip

Sorry about our server issue!
