### ISSUE TITLE
Would it be possible to share the source code for "Real-Time Natural Language search on HowTo100M"

### ISSUE THREAD

**Issue by yushuinanrong** [antoine77340/howto100m#8]
Hi team,

Thanks for sharing the dataset and source code for reproducing the paper results. I wonder if you could also share the source code for the demo "Real-Time Natural Language search on HowTo100M". I'm amazed by the retrieval speed so I want to learn more about it. 

Thanks

**Comment by antoine77340** [comment]
Hi,
It would be impossible for me to open-source that as I am not at Inria anymore.
But basically, the fast retrieval relies on the FAISS library: https://github.com/facebookresearch/faiss

**Comment by yushuinanrong** [comment]
@antoine77340 
Thanks. I've managed to run the FAISS code.
